export const config = {
  CRAWL_DEFAULT_DEPTH: 3,
  CRAWL_DEFAULT_DEPTH_RANGE: [1, 8],
  CRAWL_DEFAULT_BREADTH: 3,
  CRAWL_DEFAULT_BREADTH_RANGE: [1, 8],
  WEBSOCKET_API_BASEURL:
    'https://cueseuvko4.execute-api.us-east-1.amazonaws.com',
  SEARCH_API_CACHE_TTL: 3600,
  MINIMUM_SEARCH_LENGTH: 3,
  GRAPH_BASE_NODE_SIZE: 3,
}
